// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJMIXhsOjbk0fjfmPGKnCnUtl_sFenzA',
    appId: '1:259979143938:web:4567dfcbfa42156634701b',
    messagingSenderId: '259979143938',
    projectId: 'push-notifications-48339',
    authDomain: 'push-notifications-48339.firebaseapp.com',
    storageBucket: 'push-notifications-48339.firebasestorage.app',
    measurementId: 'G-QDLM3G5LBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNG-MNyttYw6796rM-XoYOYA0Forgw0jc',
    appId: '1:259979143938:android:4fdd8488e91654c034701b',
    messagingSenderId: '259979143938',
    projectId: 'push-notifications-48339',
    storageBucket: 'push-notifications-48339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALCKHbIGEyIR84EP9dwy6SgfCvkj0e3QA',
    appId: '1:259979143938:ios:c1e1bebf7b3db79534701b',
    messagingSenderId: '259979143938',
    projectId: 'push-notifications-48339',
    storageBucket: 'push-notifications-48339.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdJMIXhsOjbk0fjfmPGKnCnUtl_sFenzA',
    appId: '1:259979143938:web:9de693f0f83c00bd34701b',
    messagingSenderId: '259979143938',
    projectId: 'push-notifications-48339',
    authDomain: 'push-notifications-48339.firebaseapp.com',
    storageBucket: 'push-notifications-48339.firebasestorage.app',
    measurementId: 'G-XZ8XHDNWJC',
  );
}
